version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      # Install dependencies
      - pip install -r requirements.txt
  pre_build:
    commands:
      # Execute pre-build commands (if any)
      - echo "Executing pre-build commands..."
  build:
    commands:
      # Run tests
      - python -m unittest discover tests
  post_build:
    commands:
      # After successful build, package artifacts or deploy
      - echo "Build successful. Packaging artifacts..."
